#!/bin/bash
result=$(nmcli -t -f type,state,connection d | grep -E "^(tun|tap):connected" | awk -F':' '{ print $3 }' | tr '\n' ' ' | sed -e 's/tun0/s/; s/tun1/p/; s/tun2/a/')
[[ -z $result ]] && echo '' || echo "$result"
